export const EnvironmentUrls = {
  abtestingApiSite: "https://abtesting.roblox.com",
  accountInformationApi: "https://accountinformation.roblox.com",
  accountSettingsApi: "https://accountsettings.roblox.com",
  adConfigurationApi: "https://adconfiguration.roblox.com",
  adsApi: "https://ads.roblox.com",
  advertiseApi: "https://advertise.roblox.com",
  apiGatewayCdnUrl: "https://apis.rbxcdn.com",
  apiGatewayUrl: "https://apis.roblox.com",
  apiProxyUrl: "https://api.roblox.com",
  assetDeliveryApi: "https://assetdelivery.roblox.com",
  authApi: "https://auth.roblox.com",
  avatarApi: "https://avatar.roblox.com",
  badgesApi: "https://badges.roblox.com",
  billingApi: "https://billing.roblox.com",
  captchaApi: "https://captcha.roblox.com",
  catalogApi: "https://catalog.roblox.com",
  chatApi: "https://chat.roblox.com",
  chatModerationApi: "https://chatmoderation.roblox.com",
  contactsApi: "https://contacts.roblox.com",
  contactsServiceApi: "https://apis.roblox.com/contacts-api",
  contentStoreApi: "https://contentstore.roblox.com",
  developApi: "https://develop.roblox.com",
  domain: "roblox.com",
  economyApi: "https://economy.roblox.com",
  economycreatorstatsApi: "https://economycreatorstats.roblox.com",
  engagementPayoutsApi: "https://engagementpayouts.roblox.com",
  followingsApi: "https://followings.roblox.com",
  friendsApi: "https://friends.roblox.com",
  gameInternationalizationApi: "https://gameinternationalization.roblox.com",
  gamesApi: "https://games.roblox.com",
  gameJoinApi: "https://gamejoin.roblox.com",
  gameUpdateNotificationsApi:
    "https://apis.roblox.com/game-update-notifications",
  groupsApi: "https://groups.roblox.com",
  groupsModerationApi: "https://groupsmoderation.roblox.com",
  helpSite: "https://en.help.roblox.com",
  inventoryApi: "https://inventory.roblox.com",
  itemConfigurationApi: "https://itemconfiguration.roblox.com",
  localeApi: "https://locale.roblox.com",
  localizationTablesApi: "https://localizationtables.roblox.com",
  metricsApi: "https://metrics.roblox.com",
  midasApi: "https://midas.roblox.com",
  notificationApi: "https://notifications.roblox.com",
  passProductPurchasingApi: "https://apis.roblox.com/pass-product-purchasing",
  bundlesProductPurchasingApi:
    "https://apis.roblox.com/bundles-product-purchasing",
  premiumFeaturesApi: "https://premiumfeatures.roblox.com",
  presenceApi: "https://presence.roblox.com",
  privateMessagesApi: "https://privatemessages.roblox.com",
  publishApi: "https://publish.roblox.com",
  restrictedHoursServiceApi: "https://apis.roblox.com/restricted-hours-service",
  screenTimeApi: "https://apis.rcs.roblox.com/screen-time-api",
  shareApi: "https://share.roblox.com",
  shareLinksApi: "https://apis.roblox.com/sharelinks",
  thumbnailsApi: "https://thumbnails.roblox.com",
  tradesApi: "https://trades.roblox.com",
  translationRolesApi: "https://translationroles.roblox.com",
  twoStepVerificationApi: "https://twostepverification.roblox.com",
  universalAppConfigurationApi:
    "https://apis.roblox.com/universal-app-configuration",
  userAgreementsServiceApi: "https://apis.roblox.com/user-agreements",
  userModerationApi: "https://usermoderation.roblox.com",
  usersApi: "https://users.roblox.com",
  userSettingsApi: "https://apis.roblox.com/user-settings-api",
  voiceApi: "https://voice.roblox.com",
  websiteUrl: "https://www.roblox.com",
};
